services:
 web:
  image: nginx:latest
  container_name: nginx_php_vanilla_api
  restart: always
  ports:
   - "80:80"
  volumes:
   - ./:/www
   - ./default.conf:/etc/nginx/conf.d/default.conf
  links:
   - php

 php:
  build: .
  container_name: php_fpm_php_vanilla_api
  volumes:
   - ./:/www
  links:
   - db

 db:
  image: mysql:5.7
  container_name: mysql_db_vanilla_api
  restart: always
  ports:
   - "3310:3306"
  command: --default-authentication-plugin=mysql_native_password
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: product_db